export const Permissions = {
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_UPDATE: 'USER_UPDATE',
  USER_DELETE: 'USER_DELETE',

  BANNER_VIEW: 'BANNER_VIEW',
  BANNER_CREATE: 'BANNER_CREATE',
  BANNER_UPDATE: 'BANNER_UPDATE',
  BANNER_DELETE: 'BANNER_DELETE',

  CATEGORY_VIEW: 'CATEGORY_VIEW',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_DELETE: 'CATEGORY_DELETE',

  DEPARTMENT_VIEW: 'DEPARTMENT_VIEW',
  DEPARTMENT_CREATE: 'DEPARTMENT_CREATE',
  DEPARTMENT_UPDATE: 'DEPARTMENT_UPDATE',
  DEPARTMENT_DELETE: 'DEPARTMENT_DELETE',

  SUBSCRIPTION_VIEW: ' SUBSCRIPTION_VIEW',
  SUBSCRIPTION_CREATE: ' SUBSCRIPTION_CREATE',
  SUBSCRIPTION_UPDATE: ' SUBSCRIPTION_UPDATE',
  SUBSCRIPTION_DELETE: ' SUBSCRIPTION_DELETE',

  FEATURED_VIEW: 'FEATURED_VIEW',
  FEATURED_CREATE: 'FEATURED_CREATE',
  FEATURED_UPDATE: 'FEATURED_UPDATE',
  FEATURED_DELETE: 'FEATURED_DELETE',

  PACKAGE_VIEW: 'PACKAGE_VIEW',
  PACKAGE_CREATE: 'PACKAGE_CREATE',
  PACKAGE_UPDATE: 'PACKAGE_UPDATE',
  PACKAGE_DELETE: 'PACKAGE_DELETE',

  PRODUCT_VIEW: 'PRODUCT_VIEW',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_DELETE: 'PRODUCT_DELETE',

  PROVIDER_VIEW: 'PROVIDER_VIEW',
  PROVIDER_CREATE: 'PROVIDER_CREATE',
  PROVIDER_UPDATE: 'PROVIDER_UPDATE',
  PROVIDER_DELETE: 'PROVIDER_DELETE',

  PROVIDER_PACKAGE_VIEW: 'PROVIDER_PACKAGE_VIEW',
  PROVIDER_PACKAGE_CREATE: 'PROVIDER_PACKAGE_CREATE',
  PROVIDER_PACKAGE_UPDATE: 'PROVIDER_PACKAGE_UPDATE',
  PROVIDER_PACKAGE_DELETE: 'PROVIDER_PACKAGE_DELETE',

  PROVIDER_PRODUCT_VIEW: 'PROVIDER_PRODUCT_VIEW',
  PROVIDER_PRODUCT_CREATE: 'PROVIDER_PRODUCT_CREATE',
  PROVIDER_PRODUCT_UPDATE: 'PROVIDER_PRODUCT_UPDATE',
  PROVIDER_PRODUCT_DELETE: 'PROVIDER_PRODUCT_DELETE',

  PROVIDER_DISCOUNT_VIEW: 'PROVIDER_DISCOUNT_VIEW',
  PROVIDER_DISCOUNT_CREATE: 'PROVIDER_DISCOUNT_CREATE',
  PROVIDER_DISCOUNT_UPDATE: 'PROVIDER_DISCOUNT_UPDATE',
  PROVIDER_DISCOUNT_DELETE: 'PROVIDER_DISCOUNT_DELETE',

  PROVIDER_DEPARTMENT_VIEW: 'PROVIDER_DEPARTMENT_VIEW',
  PROVIDER_DEPARTMENT_CREATE: 'PROVIDER_DEPARTMENT_CREATE',
  PROVIDER_DEPARTMENT_UPDATE: 'PROVIDER_DEPARTMENT_UPDATE',
  PROVIDER_DEPARTMENT_DELETE: 'PROVIDER_DEPARTMENT_DELETE',

  ORDER_VIEW: 'ORDER_VIEW',
  ORDER_CREATE: 'ORDER_CREATE',
  ORDER_UPDATE: 'ORDER_UPDATE',
  ORDER_DELETE: 'ORDER_DELETE',

  ROLE_VIEW: ' ROLE_VIEW',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',

  PERMISSION_VIEW: ' PERMISSION_VIEW',
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE',
  PERMISSION_DELETE: 'PERMISSION_DELETE',

  USER_ROLE_MANAGEMENT: 'USER_ROLE_MANAGEMENT',

  ADDRESS_MANAGEMENT: 'ADDRESS_MANAGEMENT',

  FORBIDDEN: 'FORBIDDEN',
};

export type PermissionsTypes = keyof typeof Permissions;
